"""
Sprint 1: Post-Crawl Cleaning
Applies extra cleaning steps (like removing specific redundant footers) 
to the Markdown files generated by crawl4ai if needed.

Run: python ingestion/clean.py
"""

import os
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.config import RAW_WEB_DIR
from app.logger import get_logger

logger = get_logger(__name__)

def clean_markdown_files():
    """
    Iterates over all files in data/raw_web/ and applies regex or manual
    cleaning rules to remove unwanted university boilerplate.
    (crawl4ai does most of the heavy lifting, this is just for edge cases).
    """
    if not RAW_WEB_DIR.exists():
        logger.error("raw_web directory not found. Run crawl.py first.")
        return

    files = list(RAW_WEB_DIR.glob("*.md"))
    logger.info(f"Starting post-clean for {len(files)} files...")

    cleaned_count = 0
    for file_path in files:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Example: Remove a known repetitive footer
            if "جميع الحقوق محفوظة لجامعة الريادة" in content:
                content = content.split("جميع الحقوق محفوظة لجامعة الريادة")[0]
            
            # Write back
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content.strip())
            
            cleaned_count += 1
            
        except Exception as e:
            logger.error(f"Failed to clean {file_path.name}: {str(e)}")

    logger.info(f"Cleaning complete. Modified {cleaned_count} files.")

if __name__ == "__main__":
    clean_markdown_files()
